app = "clyne-paper-crm-frontend"
primary_region = "jnb"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NEXT_PUBLIC_API_URL = "https://clyne-paper-crm-backend.fly.dev/api"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://clyne-paper-crm-backend.fly.dev/api"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

[http_service]
  internal_port = 3000
  force_https = true

# Custom domain configuration
[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static"

# Handle custom domain
[experimental]
  auto_rollback = true
