#!/bin/bash

echo "🔄 Clyne Paper CRM - Data Migration Guide"
echo "=========================================="
echo ""

echo "📚 Available Migration Scripts:"
echo "------------------------------"
echo "1. export-data.js    - Export all data from local database"
echo "2. import-data.js    - Import data to production database"  
echo "3. migrate-data.js   - Complete migration (export + upload + import)"
echo ""

echo "🚀 Quick Start - Complete Migration:"
echo "-----------------------------------"
echo "node migrate-data.js"
echo ""

echo "📤 Export Only (for manual transfer):"
echo "------------------------------------"
echo "node export-data.js"
echo ""

echo "📥 Import Only (run on production):"
echo "----------------------------------"
echo "fly ssh console --app clyne-paper-crm-backend -C \"node import-data.js /app/data-export-*.json --clear --preserve-admin\""
echo ""

echo "🔧 Manual Migration Steps:"
echo "-------------------------"
echo "1. Export local data:"
echo "   node export-data.js"
echo ""
echo "2. Upload to production:"
echo "   fly ssh sftp put data-export-*.json /app/ --app clyne-paper-crm-backend"
echo ""
echo "3. Import on production:"
echo "   fly ssh console --app clyne-paper-crm-backend -C \"node import-data.js /app/data-export-*.json --clear --preserve-admin\""
echo ""

echo "⚙️ Import Options:"
echo "-----------------"
echo "--clear                 Clear existing data before import"
echo "--preserve-admin        Keep production admin user (recommended)"
echo "--skip-users           Skip user import"
echo "--skip-audit-logs      Skip audit log import"
echo ""

echo "🔒 Security Notes:"
echo "-----------------"
echo "• Production admin user (admin@clynepaper.com) is preserved by default"
echo "• User passwords are migrated (consider forcing password resets)"
echo "• Audit logs are limited to last 1000 entries to avoid huge files"
echo ""

echo "📊 What gets migrated:"
echo "---------------------"
echo "✅ Roles and permissions"
echo "✅ Regions and teams"
echo "✅ Users (with preserved passwords)"
echo "✅ Customers"
echo "✅ Inventory items"
echo "✅ Waybills and items"
echo "✅ Invoices and items"
echo "✅ Audit logs (last 1000)"
echo ""

echo "❓ Need help? Run:"
echo "node migrate-data.js --help"
