name: Deploy Backend to Fly.io

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Fly app name"
        required: true
        default: "clyne-paper-crm-backend"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config backend/fly.toml --remote-only -a "${{ github.event.inputs.app_name }}"
